version: '3'

services:
  db:
    image: postgres:15
    container_name: testing-db
    restart: always
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nebuladb
